### ISSUE TITLE
Seismon still referencing deprecated gwpy.spectrum module

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/seismon#1]
As reported in a LIGO internal ticket, `seismon` is still referencing the deprecated `gwpy.spectrum` module. This should be replaced with `gwpy.frequencyseries`. Any object references to the `gwpy.spectrum.Spectrum` should similarly be updated to use `gwpy.frequencyseries.FrequencySeries`.

**Comment by duncanmmacleod** [comment]
@mcoughlin, does c2341fa fix this?

**Comment by mcoughlin** [comment]
Should be good enough for now.
